name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packaging requests xmltodict
    - name: Setup Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
    - name: Update
      run: |
        cd jetbrains
        python3 update.py
    - name: Commit
      run: |
        git add -A
        git commit -m "Version bump"
        git push
